name: lottery_fly
description: Lottery application for Canada Australia NZ USA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.0
  flutter_local_notifications: ^17.0.0
  pdf: ^3.10.0
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    
